# -*- coding: utf-8 -*-
"""trabalho_pratico_modulo2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b0H6iC_yW5qzAXtNbYEGG1j7EFwuAe_F

# Trabalho Prático - Módulo 2

## Enunciado

1. Acessar o ambiente Google Colaboratory(recomendado) ou qualquer ambiente de desenvolvimento em Python.
"""

from google.colab import files
uploaded = files.upload()

"""2. Importar as bibliotecas do numpy e pandas conforme:"""

import numpy as np
import pandas as pd

"""Carregar o dataset https://pycourse.s3.amazonaws.com/bike-sharing.csv para análise utilizando o pandas. Exemplo:"""

df = pd.read_csv("bike-sharing.csv")

df.head()

"""A seguir, um descritivo dos dados coletados:

- **rec_id:** índice do registro de locação;

- **datetime:** data;

- **season:** estação do ano (1: inverno, 2: primavera, 3: verão, 4: outono). Relativo ao hemisfério norte;

- **year:** ano (0: 2011, 1:2012);

- **month:** mês (1 a 12);

- **hour:** hora do dia (0 a 23);

- **is_holiday:** booleano indicando feriado;

- **weekday:** dia da semana (0: domingo, 1: segunda-feira, …, 6: sábado);

- **is_workingday:** booleano indicando dia útil;

- **weather_condition:** (1: limpo, 2: nublado, 3: chuva leve, 4: chuva forte);

- **temp:** temperatura escalada entre 0 e 1. Valor original em graus Celsius: -8 a 39;

- **atemp:** sensação térmica escalada entre 0 e 1. Valor original em graus Celsius: -16 a 50;

- **humidity:** humidade relativa (0 a 1);

- **windspeed:** velocidade do vento escalada entre 0 e 1 (máximo original: 67);

- **casual:** número de locações para usuários casuais;

- **registered:** número de locações para usuários registrados;

- **total_count:** contador total de aluguéis (casual+registered).

4. Responda às seguintes perguntas:

a. Qual o tamanho desse dataset? (número de linhas, número de colunas)
"""

df.shape

"""b. Qual a média da coluna windspeed?"""

df['windspeed'].mean()

"""c. Qual a média da coluna temp?"""

df['temp'].mean()

"""d. Quantos registros existem para o ano de 2011? (número de linhas, número de colunas)"""

df[df['year'] == 0].shape

"""e. Quantos registros existem para o ano de 2012? (número de linhas, número de colunas)"""

df[df['year'] == 1].shape

"""f. Quantas locações de bicicletas foram efetuadas em 2011?"""

df[df['year'] == 0]['total_count'].sum()

"""g. Quantas locações de bicicletas foram efetuadas em 2012?"""

df[df['year'] == 1]['total_count'].sum()

"""h. Qual estação do ano contém a maior média de locações de bicicletas?"""

df.groupby('season').agg('mean')['total_count'].sort_values(ascending=False).head(1)

"""i. Qual estação do ano contém a menor média de locações de bicicletas?"""

df.groupby('season').agg('mean')['total_count'].sort_values(ascending=True).head(1)

"""j. Qual horário do dia contém a maior média de locações de bicicletas?"""

df.groupby('hour').agg('mean')['total_count'].sort_values(ascending=False).head(1)

"""k. Qual horário do dia contém a menor média de locações de bicicletas?"""

df.groupby('hour').agg('mean')['total_count'].sort_values(ascending=True).head(1)

"""l. Que dia da semana contém a maior média de locações de bicicletas?"""

df.groupby('weekday').agg('mean')['total_count'].sort_values(ascending=False).head(1)

"""m. Que dia da semana contém a menor média de locações de bicicletas?"""

df.groupby('weekday').agg('mean')['total_count'].sort_values(ascending=True).head(1)

"""n. Às quartas-feiras (weekday = 3), qual o horário do dia contém a maior média de locações de bicicletas?"""

df[df['weekday'] == 3].groupby('hour').agg('mean')['total_count'].sort_values(ascending=False).head(1)

"""o. Aos sábados (weekday = 6), qual o horário do dia contém a maior média de locações de bicicletas?"""

df[df['weekday'] == 6].groupby('hour').agg('mean')['total_count'].sort_values(ascending=False).head(1)